language: node_js
node_js:
  - 16
  - 15
  - 14
  - 12
jobs:
  include:
    - stage: Coveralls Test Coverage
      node_js: node
      script: npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
