language: node_js
node_js:
  - 15
  - 14
  - 12
env:
  jobs:
    - MONGOMS_VERSION=3.6.23
    - MONGOMS_VERSION=4.2.8
jobs:
  include:
    - stage: Coveralls Test Coverage
      node_js: node
      script: npm run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
